### ISSUE TITLE
timeout for pygnmi subscribe generator

### ISSUE THREAD

**Issue by slieberth** [akarneliuk/pygnmi#4]
Hi Anton, 

many thanks for providing this library.
Actually this request is more a question than an issue ... 

I consider using pygnmi for a testing environment and for this use case I would need a timeout for subscribe generator. 

I have implemented a wrapper class (based on kthreads and queues)  and that serve my needs 
https://github.com/slieberth/gnmi_subscribe_timeout/blob/main/gnmi_subscribe_timeout.py

Do you think a timeout for the pygnmi subscribe generator? 
( I can contribute, if you wish ... )

beste regards 
Stefan

**Comment by akarneliuk** [comment]
Hey @slieberth ,

Thanks for reaching us out. What you have shared seems reasonable. We are open to all the contribution, so you are welcome to do thta. I am thinking, we could try to add that to telemetryParser class directly. Not sure, but i think worth a try.

So that we understand the goal: if tje device doesn't push telemetry when it shall, you propose to terminate session to avoid waiting for infinity. Is my understanding accurate?

Best,
Anton

**Comment by slieberth** [comment]
Hi Anton,

yes, the goal is a void waiting for infinity in case there is a malfunction on the router side.

I am happy to contribute, pls give me 1-2 weeks for a proposal 

regards Stefan

**Comment by akarneliuk** [comment]
Hello @slieberth ,

I believe I saw your addition in the code. Do you have any examples how that is working, please?

Thanks,
Anton

**Comment by akarneliuk** [comment]
Hello @slieberth ,

is this issue related to your latest commit, sir? Is that still open or if that can be closed?

Thanks,
Anton

**Comment by akarneliuk** [comment]
Hello @slieberth ,

I'm closing the issue as there is no follow up.

Best,
Anton
